name: asv-benchmarks

on:
  # Trigger the workflow on push to the master branch
  push:
    branches:
      - master

jobs:

  # Run the asv benchmarks on the self-hosted runner
  benchmarks:
    name: benchmarks
    runs-on: ubuntu-18.04

    env:
      DEVITO_ARCH: "gcc-9"
      DEVITO_LANGUAGE: "openmp"
      DEVITO_BENCHMARKS: "1"
      DEVITO_LOGGING: "PERF"
      OMP_NUM_THREADS: "8"
      CC: "gcc-9"
      CXX: "g++-9"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install asv

    - name: Setup asv
      run: |
        asv machine --config benchmarks/regression/asv.conf.json --machine mymachine

    - name: Run benchmarks
      run: |
        asv run -v --show-stderr --config benchmarks/regression/asv.conf.json --machine mymachine --cpu-affinity 0-1

    - name: Stash ASV results  #TODO: otherwise ditched by the checkout action below
      run: |
        mkdir -p /tmp/asv-results/mymachine
        mv benchmarks/regression/.asv/results/benchmarks.json /tmp/asv-results
        mv benchmarks/regression/.asv/results/mymachine/*py*.json /tmp/asv-results/mymachine/

    - name: Checkout asv-results branch
      uses: actions/checkout@v1
      with:
        ref: asv-results

    - name: Commit results
      run: |
        mv /tmp/asv-results/benchmarks.json benchmarks/regression/.asv/results
        mkdir -p benchmarks/regression/.asv/results/mymachine/  #TODO eventually this wont be necessary
        mv /tmp/asv-results/mymachine/* benchmarks/regression/.asv/results/mymachine/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add benchmarks/regression/.asv/results
        git commit -m "Commit ASV results"

    - name: Push results to the asv-results branch
      uses: ad-m/github-push-action@master
      with:
        branch: asv-results
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create results (html)
      run: |
        asv publish --config benchmarks/regression/asv.conf.json

#    - name: Deploy results to devitocodes/devito-performance/gh-pages
#      uses: peaceiris/actions-gh-pages@v2.5.0
#      env:
#        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#        EXTERNAL_REPOSITORY: devitocodes/devito-performance
#        PUBLISH_BRANCH: gh-pages
#        PUBLISH_DIR: ./benchmarks/regression/.asv/html
