name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: | 
        docker build . --file docker/Dockerfile --tag my-image-name:$(date +%s)
        docker run --name testrun my-image-name:$(date +%s)
